routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::get('/agenda/create', 'HomeController@create')->name('home.create');
Route::get('/', 'HomeController@index')->name('home');

Route::group(['middleware' => ['auth']], function () {

    Route::post('/list', 'UserController@list')->name('user.account.list');
    Route::resource('user', 'UserController')->except(['destroy']);

    Route::resource('agenda', 'AgendaController')->except(['destroy']);
    Route::prefix('agenda')->name('agenda.')->group( function () {
        Route::post('/list', 'AgendaController@list')->name('list');
    });
});

app/Agenda.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use App\Traits\Uuids;
use App\AgendaUserPosition;
use App\AgendaUser;
use App\User;

class Agenda extends Model implements \MaddHatter\LaravelFullcalendar\IdentifiableEvent
{
    use Uuids;

    protected $fillable = ['name', 'description', 'destination', 'start_time', 'end_time'];
    protected $dates = ['start_time', 'end_time', 'created_at', 'updated_at'];

    public function agendaUsers() {
        return $this->hasMany('App\AgendaUser', 'agenda_id');
    }

    public function users() {
        return $this->belongsToMany('App\User', 'agenda_users')->using('App\AgendaUser')->withTimestamps()->withPivot('created_at')->orderBy('users.name', 'asc');
    }

    public function log() {
        return $this->hasMany('App\Log', 'agenda_id', 'id');
    }

    /**
     * Get the event's id number
     *
     * @return int
     */
    public function getId() {
		return $this->id;
	}

    /**
     * Get the event's title
     *
     * @return string
     */
    public function getTitle()
    {
        return $this->title;
    }

    /**
     * Is it an all day event?
     *
     * @return bool
     */
    public function isAllDay()
    {
        return (bool)$this->all_day;
    }

    /**
     * Get the start time
     *
     * @return DateTime
     */
    public function getStart()
    {
        return $this->start_time;
    }

    /**
     * Get the end time
     *
     * @return DateTime
     */
    public function getEnd()
    {
        return $this->end_time;
    }
}

app/Http/Controllers/AgendaController.php
<?php

namespace App\Http\Controllers;

use App\User;
use App\Agenda;
use App\position;
use App\AgendaUser;
use DataTables;
use Illuminate\Http\Request;

class AgendaController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $view = [
            'title' => 'Agenda Kegiatan',
        ];

        return view('agenda.index', $view);
    }

    /**
     * Show a listing of the resource for datatable.
     * 
     * @param  \Illuminate\Http\Request  $request
     */
    public function list(Request $request)
    {
        if ($request->ajax()) {
            $agenda = Agenda::get();
            return DataTables::of($agenda)
                ->addColumn('DT_RowIndex', function ($data) {
                    return '<div class="checkbox icheck"><label><input type="checkbox" name="selectedData[]" value="'.$data->id.'"></label></div>';
                })
                ->editColumn('created_at', function($data) {
                    return (date('d-m-Y H:i:s', strtotime($data->created_at)));
                })
                ->editColumn('name', function($data) {
                    $explode = explode('\n', $data->name);
                    return implode(', ',$explode);
                })
                ->editColumn('start_time', function($data) {
                    return (date('l, F, d H:i:s', strtotime($data->start_time)));
                })
                ->editColumn('end_time', function($data) {
                    return (date('l, F, d H:i:s', strtotime($data->end_time)));
                })
                ->addColumn('action', function($data) {
                    return '<a class="btn btn-sm btn-info" href="'.route('agenda.show', $data->id).'" title="'.__('See detail').'"><i class="fa fa-eye"></i> '.__('See').'</a> <a class="btn btn-sm btn-warning" href="'.route('agenda.edit', $data->id).'" title="'.__('Edit').'"><i class="fa fa-edit"></i> '.__('Edit').'</a>';
                })
                ->rawColumns(['DT_RowIndex', 'action'])
                ->make(true);
        }
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $view = [
            'title' => 'Create',
            'type' => [
                'pujian' => 'Pujian', 
                'doa' => 'Doa dan konselor', 
                'pewarta' => 'Pewarta & Pengajar'
            ],
            'users' => User::pluck('name', 'name')->toArray(),
        ];

        return view('agenda.create', $view);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        if ($request->end_time) {
            $this->validate($request, [
                'name' => 'required',
                'start_time' => 'required',
                'end_time' => 'after_or_equal:start_time'
            ]); 
        }else{
            $this->validate($request, [
                'name' => 'required',
                'start_time' => 'required',
            ]); 
        }
        $name = '';
        if (!empty($request->name)) { $name .= ' ' . $request->name . ' \n '; }
        if (!empty($request->pembicara)) { $name .= 'Pembicara : ' . $request->pembicara . ' \n '; }
        if (!empty($request->leader)) { $name .= 'WL : ' . implode(', ', $request->leader) . ' \n '; }
        if (!empty($request->pemusik)) { $name .= 'Pemusik : ' . implode(', ', $request->pemusik) . ' \n '; }
        if (!empty($request->mulmed)) { $name .= 'Mulmed : ' . implode(', ', $request->mulmed) . ' \n '; }
        if (!empty($request->singer)) { $name .= 'Singer : ' . implode(', ', $request->singer) . ' \n '; }
        if (!empty($request->pewarta)) { $name .= 'Pewarta : ' . $request->pewarta . ' \n '; }

        $description = '';
        if (!empty($request->tema)) { $description .= ' Tema : ' . $request->tema . ' \n '; }
        if (!empty($request->pendoa)) { $description .= 'Konselor / pendoa : ' . $request->pendoa . ' \n '; }
        if (!empty($request->kegiatan)) { $description .= 'Kegiatan : ' . $request->kegiatan . ' \n '; }
        if (!empty($request->konseliName)) { $description .= 'Konseli / yang didoakan : ' . $request->konseliName . ' \n '; }
        $request->merge([
            'name' => $name,
            'description' => $description . $request->description,
        ]);

        $agenda = Agenda::create($request->all());

        // if($agenda) {
        //     foreach ($request->position as $position => $value) {
        //         $position_id = Position::where('name' , $position)->select('id')->first()->id;
        //         if(is_array($value)) {
        //             foreach ($value as $user_id) {
        //                 if ($user_id) {
        //                     $agenda->agendaUsers()->create([
        //                         'user_id' => $user_id,
        //                         'position_id' => $position_id
        //                     ]);
        //                 }
        //             }
        //         }else{
        //             if ($value) {
        //                 $agenda->agendaUsers()->create([
        //                     'user_id' => $value,
        //                     'position_id' => $position_id
        //                 ]);
        //             }
        //         }
        //     }
        // }

        return redirect()->route('home')->with('alert-success', 'Create success!');        
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Agenda  $agenda
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $pembicara = '';
        $wl = '';
        $pemusik = '';
        $mulmed = '';
        $singer = '';
        $pewarta = '';
        $agenda = Agenda::find($id);
        $explode = explode('\n', $agenda->name);
        $kegiatan = $explode[0];
        foreach ($explode as $key) {
            preg_match('/Pembicara/i', $key) ? $pembicara = $key : '';
            preg_match('/WL/i', $key) ? $wl = $key : '';
            preg_match('/Pemusik/i', $key) ? $pemusik = $key : '';
            preg_match('/Mulmed/i', $key) ? $mulmed = $key : '';
            preg_match('/Singer/i', $key) ? $singer = $key : '';
            preg_match('/Pewarta/i', $key) ? $pewarta = $key : '';
        }
        $view = [
            'title' => 'Agenda',
            'agenda' => $agenda,
            'kegiatan' => $kegiatan,
            'pembicara' => $pembicara,
            'wl' => $wl,
            'pemusik' => $pemusik,
            'mulmed' => $mulmed,
            'singer' => $singer,
            'pewarta' => $pewarta,
        ];

        return view('agenda.show', $view);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Agenda  $agenda
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $pembicara = '';
        $wl = '';
        $pemusik = '';
        $mulmed = '';
        $singer = '';
        $pewarta = '';
        $agenda = Agenda::find($id);
        $explode = explode('\n', $agenda->name);
        $kegiatan = $explode[0];
        foreach ($explode as $key) {
            preg_match('/Pembicara/i', $key) ? $pembicara = $key : '';
            preg_match('/WL/i', $key) ? $wl = $key : '';
            preg_match('/Pemusik/i', $key) ? $pemusik = $key : '';
            preg_match('/Mulmed/i', $key) ? $mulmed = $key : '';
            preg_match('/Singer/i', $key) ? $singer = $key : '';
            preg_match('/Pewarta/i', $key) ? $pewarta = $key : '';
        }
        $view = [
            'title' => 'Agenda',
            'agenda' => $agenda,
            'kegiatan' => $kegiatan,
            'pembicara' => $pembicara,
            'wl' => $wl,
            'pemusik' => $pemusik,
            'mulmed' => $mulmed,
            'singer' => $singer,
            'pewarta' => $pewarta,
        ];

        return view('agenda.edit', $view);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Agenda  $agenda
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Agenda $agenda)
    {
        $name = '';
        if (!empty($request->name)) { $name .= ' ' . $request->name . ' \n '; }
        if (!empty($request->pembicara)) { $name .= 'Pembicara : ' . $request->pembicara . ' \n '; }
        if (!empty($request->leader)) { $name .= 'WL : ' . $request->leader . ' \n '; }
        if (!empty($request->pemusik)) { $name .= 'Pemusik : ' . $request->pemusik . ' \n '; }
        if (!empty($request->mulmed)) { $name .= 'Mulmed : ' . $request->mulmed . ' \n '; }
        if (!empty($request->singer)) { $name .= 'Singer : ' . $request->singer . ' \n '; }
        if (!empty($request->pewarta)) { $name .= 'Pewarta : ' . $request->pewarta . ' \n '; }

        $request->merge([
            'name' => $name,
        ]);

        $agenda->fill($request->all());

        $agenda->save();
        return redirect()->route('agenda.index')->with('alert-success', 'Agenda has been changed!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Agenda  $agenda
     * @return \Illuminate\Http\Response
     */
    public function destroy(Agenda $agenda)
    {
        //
    }
}

resources/views/agenda/create.blade.php
@extends('layouts.main')
@section('content')

        @if (session('alert-success'))
            <div class="alert alert-success alert-dismissible show fade">
                <div class="alert-body">
                    <button class="close" data-dismiss="alert">
                        <span>&times;</span>
                    </button>
                    {{ session('alert-success') }}
                </div>
            </div>
        @endif

        @if (session('alert-danger'))
            <div class="alert alert-danger alert-dismissible show fade">
                <div class="alert-body">
                    <button class="close" data-dismiss="alert">
                        <span>&times;</span>
                    </button>
                    {{ session('alert-danger') }}
                </div>
            </div>
        @endif

        <div class="card">
            <div class="card-header">
                <h4>{{ __('Tambah Agenda') }}</h4>
            </div>
            {{ Form::open(['route' => 'agenda.store', 'files' => true]) }}
            <div class="card-body">
                <div class="row">
                    <div class="col-sm-6 col-lg-3">
                    </div>
                    <div class="col-sm-6 col-lg-9">
                        <label style="color: red">*Kosongkan field yang tidak di perlukan</label>
                    </div>
                    <div class="col-sm-6 col-lg-3">
                        {{ Form::bsSelect('', 'Jenis Kegiatan', 'type', $type, null, __('Pilih Jenis Kegiatan')) }}
                    </div>
                    <div class="col-sm-6 col-lg-9">
                        {{ Form::bsText(null, 'Nama Kegiatan', 'name', old('nama agenda'), __('Nama Agenda')) }}

                        {{ Form::bsText(null, 'Tujuan acara', 'destination', (empty(old('destination'))?'PDPKK ST. Laurentius Bandung':old('destination')), __('Destination')) }}


                        <div class="row">
                            {{ Form::bsText('col-md-6', 'Waktu', 'start_time', old('start_time'), __('datetime')) }}
                            <div class="col-md-1">
                                End <input type="radio" name="radio" id="radio">
                            </div>
                            <div class="col-md-5 radio-check d-none">                                {{ Form::bsText(null, ' ', 'end_time', old('end_time'), __('datetime')) }}
                            </div>
                        </div>

                        <div class="pujian d-block">
                            <div class="row">
                                {{ Form::bsText('col-md-6', 'Pembicara', 'pembicara', old('Pembicara'), __('Ex : Dimas'), ['' => '']) }}

                                {{ Form::bsSelect('col-md-6', 'Worship Leader', 'leader[]', $users, null, __('Select WL'), ['Multiple' => '']) }}

                                {{ Form::bsSelect('col-md-6', 'Pemusik', 'pemusik[]', $users, null, __('Select Pemusik'), ['Multiple' => '']) }}

                                {{ Form::bsSelect('col-md-6', 'Mulmed', 'mulmed[]', $users, null, __('Select Mulmed'), ['Multiple' => '']) }}


                                {{ Form::bsSelect('col-md-12', 'Singer', 'singer[]', $users, null, __('Select Singer'), ['Multiple' => '']) }}
                            </div>
                        </div>

                        <div class="pewarta d-none">
                            {{ Form::bsText(null, 'Pewarta', 'pewarta', old('pewarta'), __('Ex : Dimas / Dimas & Budi / Dimas, Budi, & Aji'), ['' => '']) }}

                            {{ Form::bsText(null, 'Tema', 'tema', old('tema'), __('tema pewartaan/ bahan pengajaran')) }}
                            
                        </div>

                        <div class="doa d-none">

                            {{ Form::bsText(null, 'Nama pendoa / konselor', 'pendoa', old('pendoa'), __('Nama Pendoa')) }}

                            {{ Form::bsSelect(null, __('Kegiatan'), 'kegiatan', ['Mendoakan' => 'Mendoakan', 'Konseling' => 'Konseling', 'Konseling dan Mendoakan' => 'Konseling dan Mendoakan'], null, __('Pilih kegiatan'), ['placeholder' => 'Pilih Kegiatan']) }}
                            
                            {{ Form::bsText(null, 'Nama konseli / yang didoakan', 'konseliName', old('konseliName'), __('Nama konseli / yang didoakan')) }}
                            
                        </div>
                        {{ Form::bsTextarea(null, __('Deskripsi tambahan (optional)/ keterangan'), 'description', old('description'), __('Description')) }}
                    </div>
                </div>
            </div>
            <div class="card-footer text-center">
                {{ Form::submit(__('Save'), ['name' => 'submit', 'class' => 'btn btn-primary']) }}
                {{ link_to(route('agenda.index'), __('Cancel'), ['class' => 'btn btn-danger']) }}
            </div>
            {{ Form::close() }}
        </div>
@endsection

@section('script')
<script>
    $(document).ready(function () {
        $('.pewarta select').append('<option value="" selected="true">Choose Pewarta</option>');
        $('[name="type"]').change(function(){
            $('.doa, .pewarta, .pujian').addClass('d-none').removeClass('d-block');
            $('.' + $(this).val()).addClass('d-block').removeClass('d-none');
        })
        $('[name="start_time"]').daterangepicker({
        	locale: {format: 'YYYY-MM-DD HH:mm:ss'},
        	singleDatePicker: true,
            timePicker: true,
            timePicker24Hour: true,
      	});
        $('input[name="radio"]').change(function(e) { 
            $('.radio-check').addClass('d-block').removeClass('d-none');
            $('[name="end_time"]').daterangepicker({
                locale: {format: 'YYYY-MM-DD HH:mm:ss'},
                singleDatePicker: true,
                timePicker: true,
                timePicker24Hour: true,
            });
        });
        $('select[name="leader[]"]').change(function(e) { 
            $('select[name="pemusik[]"] option, select[name="mulmed[]"] option, select[name="singer[]"] option').remove();
            @foreach ($users as $user)
                $('select[name="pemusik[]"], select[name="mulmed[]"], select[name="singer[]"]').append('<option value="{{ $user }}">{{ $user }}</option>');
            @endforeach
            let val = $(this).val();
            val.forEach(function (value) {
                $('select[name="pemusik[]"] option[value="'+ value +'"]').remove();
                $('select[name="mulmed[]"] option[value="'+ value +'"]').remove();
                $('select[name="singer[]"] option[value="'+ value +'"]').remove();
            });
        });
    });

    function allowDrop(ev) {
      ev.preventDefault();
    }

    function drag(ev) {
      ev.dataTransfer.setData("text", ev.target.id);
    }

    function drop(ev) {
      ev.preventDefault();
      var data = ev.dataTransfer.getData("text");
      ev.target.appendChild(document.getElementById(data));
    }
</script>
@endsection

resources/views/agenda/edit.blade.php
@extends('layouts.main')

@section('content')
<div class="row">
    <div class="col-12">

        @if (session('alert-success'))
            <div class="alert alert-success alert-dismissible show fade">
                <div class="alert-body">
                    <button class="close" data-dismiss="alert">
                        <span>&times;</span>
                    </button>
                    {{ session('alert-success') }}
                </div>
            </div>
        @endif

        @if (session('alert-danger'))
            <div class="alert alert-danger alert-dismissible show fade">
                <div class="alert-body">
                    <button class="close" data-dismiss="alert">
                        <span>&times;</span>
                    </button>
                    {{ session('alert-danger') }}
                </div>
            </div>
        @endif

        <div class="card card-primary">

            {{ Form::open(['route' => ['agenda.update', $agenda->id], 'method' => 'put', 'files' => true]) }}
                <div class="card-body">
                    <div class="row">

                        {{ Form::bsText('col-sm-6', __('Kegiatan'), 'name', $kegiatan, __('Name'), ['required' => '']) }}

                        {{ Form::bsText('col-sm-6', __('Destination'), 'destination', $agenda->destination, __('destination'), ['required' => '']) }}


                        {{ Form::bsText('col-md-6', 'Tanggal pelayanan', 'start_time', $agenda->start_time, __('datetime')) }}

                        {{ Form::bsText('col-md-6', 'Sampai', 'end_time', $agenda->end_time, __('datetime')) }}

                        {{ Form::bsText('col-md-6', 'Pembicara', 'pembicara', $pembicara, __('Ex : Dimas / Dimas & Budi / Dimas, Budi, & Aji'), ['' => '']) }}

                        {{ Form::bsText('col-md-6', 'Worship Leader', 'leader', $wl, __('Ex : Dimas / Dimas & Budi / Dimas, Budi, & Aji'), ['' => '']) }}

                        {{ Form::bsText('col-md-6', 'Pemusik', 'pemusik', $pemusik, __('Ex : Dimas / Dimas & Budi / Dimas, Budi, & Aji'), ['' => '']) }}

                        {{ Form::bsText('col-md-6', 'Mulmed', 'mulmed', $mulmed, __('Ex : Dimas / Dimas & Budi / Dimas, Budi, & Aji'), ['' => '']) }}


                        {{ Form::bsText('col-md-12', 'Singer', 'singer', $singer, __('Ex : Dimas / Dimas & Budi / Dimas, Budi, & Aji'), ['' => '']) }}
                    </div>
                </div>
                <div class="card-footer bg-whitesmoke text-center">
                    {{ Form::submit(__('Save'), ['name' => 'submit', 'class' => 'btn btn-primary']) }}
                    {{ link_to(url()->previous(), __('Cancel'), ['class' => 'btn btn-danger']) }}
                </div>
            {{ Form::close() }}

        </div>
    </div>
</div>
@endsection

@section('script')
<script>
    $(document).ready(function () { 
        $('[name="start_time"], [name="end_time"]').daterangepicker({
            locale: {format: 'YYYY-MM-DD HH:mm:ss'},
            singleDatePicker: true,
            timePicker: true,
            timePicker24Hour: true,
        });
    });
</script>
@endsection

resources/views/agenda/index.blade.php
@extends('layouts.main')

@section('content')
<div class="row">
	<div class="col-12">

		@if (session('alert-success'))
			<div class="alert alert-success alert-dismissible show fade">
				<div class="alert-body">
					<button class="close" data-dismiss="alert">
						<span>&times;</span>
					</button>
					{{ session('alert-success') }}
				</div>
			</div>
		@endif

		@if (session('alert-danger'))
			<div class="alert alert-danger alert-dismissible show fade">
				<div class="alert-body">
					<button class="close" data-dismiss="alert">
						<span>&times;</span>
					</button>
					{{ session('alert-danger') }}
				</div>
			</div>
		@endif

		<div class="card card-primary">
			<div class="card-header">
				<a href="{{ route('agenda.create') }}" class="btn btn-icon btn-success" target="_blank"><i class="fa fa-plus"></i> Create Agenda</a>
				<!-- <button class="btn btn-icon btn-secondary" data-toggle="modal" data-target="#filterModal" title="{{ __('Filter') }}"><i class="fa fa-filter"></i></button> -->
            	<!-- <button class="btn btn-icon btn-secondary" onclick="reloadTable()" title="{{ __('Refresh') }}"><i class="fa fa-sync"></i></i></button> -->
			</div>
			<div class="card-body">
				<div class="table-responsive">
					<table class="table table-striped" id="table4data">
						<thead>
							<tr>
								<th>
									<div class="checkbox icheck"><label><input type="checkbox" name="selectData"></label></div>
								</th>
								<th>{{ __('Created At') }}</th>
								<th>{{ __('Kegiatan') }}</th>
								<th>{{ __('Alamat') }}</th>
								<th>{{ __('Mulai') }}</th>
								<th>{{ __('Selesai') }}</th>
								<th>{{ __('Action') }}</th>
							</tr>
						</thead>
						<tbody>
						</tbody>
					</table>
				</div>
			</div>
		</div>

	</div>
</div>
@endsection

@section('script')
<script>
	var table;
	$(document).ready(function() {
		table = $('#table4data').DataTable({
			processing: true,
			serverSide: true,
			"ajax": {
				"url": "{{ route('agenda.list') }}",
				"type": "POST",
				"data": function (d) {
				  d._token = "{{ csrf_token() }}";
				  d.type = $('select[name="type"]').val();
		        }
			},
			columns: [
				{ data: 'DT_RowIndex', name: 'DT_RowIndex', 'searchable': false },
				{ data: 'created_at', name: 'created_at' },
				{ data: 'name', name: 'name' },
				{ data: 'destination', name: 'destination' },
				{ data: 'start_time', name: 'start_time' },
				{ data: 'end_time', name: 'end_time' },
				{ data: 'action', name: 'action', "orderable": false, 'searchable': false }
			],
			"order": [[ 1, 'desc' ]],
			"columnDefs": [
			{   
          		"targets": [ 0, -1 ], //last column
          		"orderable": false, //set not orderable
      		},
      		],
      		"drawCallback": function(settings) {
      			$('input[name="selectData"], input[name="selectedData[]"]').iCheck({
      				checkboxClass: 'icheckbox_flat-green',
      				radioClass: 'iradio_flat-green',
      				increaseArea: '20%' /* optional */
      			});
      			$('[name="selectData"]').on('ifChecked', function(event){
      				$('[name="selectedData[]"]').iCheck('check');
      			}).on('ifUnchecked', function(event){
      				$('[name="selectedData[]"]').iCheck('uncheck');
      			});
      		},
  		});

		$('[name="deleteData"]').click(function(event) {
			if ($('[name="selectedData[]"]:checked').length > 0) {
				event.preventDefault();
				var selectedData = $('[name="selectedData[]"]:checked').map(function(){
					return $(this).val();
				}).get();
				swal({
			      	title: '{{ __("Are you sure want to delete this data?") }}',
			      	text: '',
			      	icon: 'warning',
			      	buttons: ['{{ __("Cancel") }}', true],
			      	dangerMode: true,
			    })
			    .then((willDelete) => {
			      	if (willDelete) {
			      		$.ajax({
							url : "{{ route('user.index') }}",
							type: "DELETE",
							dataType: "JSON",
							data: {"_token" : "{{ csrf_token() }}", "selectedData" : selectedData},
							success: function(data)
							{
								reloadTable();
							},
							error: function (jqXHR, textStatus, errorThrown)
							{
								if (JSON.parse(jqXHR.responseText).status) {
									swal("{{ __('Failed!') }}", '{{ __("Data cannot be deleted.") }}', "warning");
								} else {
									swal(JSON.parse(jqXHR.responseText).message, "", "error");
								}
							}
						});
			      	}
    			});
			} else {
				swal("{{ __('Please select a data..') }}", "", "warning");
			}
		});

	});

	function reloadTable() {
	    table.ajax.reload(null,false); //reload datatable ajax
	    $('[name="selectData"]').iCheck('uncheck');
	}

	function filter() {
		reloadTable();
		$('#filterModal').modal('hide');
	}
</script>
@endsection

resources/views/agenda/show.blade.php
@extends('layouts.main')

@section('content')
<div class="row">
    <div class="col-12">

        @if (session('alert-success'))
            <div class="alert alert-success alert-dismissible show fade">
                <div class="alert-body">
                    <button class="close" data-dismiss="alert">
                        <span>&times;</span>
                    </button>
                    {{ session('alert-success') }}
                </div>
            </div>
        @endif

        @if (session('alert-danger'))
            <div class="alert alert-danger alert-dismissible show fade">
                <div class="alert-body">
                    <button class="close" data-dismiss="alert">
                        <span>&times;</span>
                    </button>
                    {{ session('alert-danger') }}
                </div>
            </div>
        @endif

        <div class="card card-primary">
            <div class="card-body">
                <div class="row">

                        {{ Form::bsText('col-sm-6', __('Kegiatan'), 'name', $kegiatan, __('Name'), ['readonly' => '']) }}

                        {{ Form::bsText('col-sm-6', __('Destination'), 'destination', $agenda->destination, __('destination'), ['readonly' => '']) }}


                        {{ Form::bsText('col-md-6', 'Tanggal pelayanan', 'start_time', $agenda->start_time, __('datetime'), ['readonly' => '']) }}

                        {{ Form::bsText('col-md-6', 'Sampai', 'end_time', $agenda->end_time, __('datetime'), ['readonly' => '']) }}

                        {{ Form::bsText('col-md-6', 'Pembicara', 'pembicara', $pembicara, __(' '), ['readonly' => '']) }}

                        {{ Form::bsText('col-md-6', 'Worship Leader', 'leader', $wl, __(' '), ['readonly' => '']) }}

                        {{ Form::bsText('col-md-6', 'Pemusik', 'pemusik', $pemusik, __(' '), ['readonly' => '']) }}

                        {{ Form::bsText('col-md-6', 'Mulmed', 'mulmed', $mulmed, __(' '), ['readonly' => '']) }}


                        {{ Form::bsText('col-md-12', 'Singer', 'singer', $singer, __(' '), ['readonly' => '']) }}
                </div>
            </div>
            <div class="card-footer bg-whitesmoke text-center">
                {{ link_to(url()->previous(), __('Cancel'), ['class' => 'btn btn-danger']) }}
            </div>
        </div>
    </div>
</div>
@endsection

@section('script')
@endsection